// Generated by modbots-backend/scripts/sign-inference-manifest.mjs.
export const inferenceManifestKeyId = "manifest-2d9552e5c411e4da";
export const inferenceManifestPublicKey = "MCowBQYDK2VwAyEArPQzS4ddmKJehPFWR5RURODbT3m+1aZKemZ+XIAfuDo=";
